<a href="https://colab.research.google.com/github/Ainurrofiq575/Latihan-UTS/blob/master/TUGAS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
NAMA = "Ainur Rofiq"
NIM  = 23090058
print("NAMA: ",NAMA, "\n", "NIM: ",NIM, "\n")
import numpy as np
VA      = [2, 4, 6, 8]
VB      = [13, 15, 17, 19]
VC      = [[10, 20, 30],[11, 22, 33]]
VD      = [[9, 7, 5],[21, 31, 41]]
vektor_a = np. array(VA)
vektor_b = np. array(VB)
vektor_c = np. array(VC)
vektor_d = np. array(VD)
print("PENJUMLAHAN & PENGURANGAN")
vektor_aplusb = vektor_a + vektor_b
print("1. Hasil Penjumlahan dari vektor VA dan vektor VB adalah =/n", str(vektor_aplusb), "/n")

vektor_dplusc = vektor_d + vektor_c
print("2. Hasil Penjumlahan dari vektor VD dan vektor VC adalah =/n", str(vektor_dplusc), "/n")

vektor_bmina = vektor_b - vektor_a
print("3. Hasil Pengurangan dari vektor VB dan vektor VA adalah =/n", str(vektor_bmina), "/n")

vektor_cmind = vektor_c - vektor_d
print("4. Hasil Pengurangan dari vektor VC dan vektor VD adalah =/n", str(vektor_cmind), "/n")

print("PERKALIAN & PEMBAGIAN")
vektor_bklia = vektor_b * vektor_a
print("1. Hasil Perkalian dari vektor VB dan vektor VA adalah =/n", str(vektor_bklia), "/n")

vektor_cklid = vektor_c * vektor_d
print("2. Hasil Perkalian dari vektor VC dan vektor VD adalah =/n", str(vektor_cklid), "/n")

vektor_bgia = vektor_b / vektor_a
print("3. Hasil Pembagian dari vektor VB dan vektor VA adalah =/n", str(vektor_bgia), "/n")

vektor_dgic = vektor_d / vektor_c
print("4. Hasil Pembagian dari vektor VD dan vektor VC adalah =/n", str(vektor_dgic), "/n")

print("PERKALIAN DOT VEKTOR")
vektor_bdota = np.dot(vektor_b, vektor_a)
print("1. Hasil Perkalian dot vektor dari vektor VB dan vektor VA adalah =/n", str(vektor_bdota), "/n")

vektor_cdotd = np.inner(vektor_c, vektor_d)
print("2. Hasil Perkalian dari vektor VC dan vektor VD adalah =/n", str(vektor_cdotd), "/n")

print("PERKALIAN SKALAR")
skalar1 = 2
vektor_ali2 = vektor_a * skalar1
print("1. Hasil dari perkalian skalar vektor a dengan 2 adalah = \n" , str(vektor_ali2), "\n")

skalar2 = 2.5
vektor_bliduma = vektor_b * skalar2
print("2. Hasil dari perkalian skalar vektor b dengan 2.5 adalah = \n" , str(vektor_bliduma), "\n")

skalar3 = 0.5
vektor_clima = vektor_c * skalar3
print("3. Hasil dari perkalian skalar vektor c dengan 0.5 adalah = \n" , str(vektor_clima), "\n")

skalar4 = 1.5
vektor_dkoma = vektor_d * skalar4
print("4. Hasil dari perkalian skalar vektor d dengan 1.5 adalah = \n" , str(vektor_dkoma), "\n")

NAMA:  Ainur Rofiq 
 NIM:  23090058 

PENJUMLAHAN & PENGURANGAN
1. Hasil Penjumlahan dari vektor VA dan vektor VB adalah =/n [15 19 23 27] /n
2. Hasil Penjumlahan dari vektor VD dan vektor VC adalah =/n [[19 27 35]
 [32 53 74]] /n
3. Hasil Pengurangan dari vektor VB dan vektor VA adalah =/n [11 11 11 11] /n
4. Hasil Pengurangan dari vektor VC dan vektor VD adalah =/n [[  1  13  25]
 [-10  -9  -8]] /n
PERKALIAN & PEMBAGIAN
1. Hasil Perkalian dari vektor VB dan vektor VA adalah =/n [ 26  60 102 152] /n
2. Hasil Perkalian dari vektor VC dan vektor VD adalah =/n [[  90  140  150]
 [ 231  682 1353]] /n
3. Hasil Pembagian dari vektor VB dan vektor VA adalah =/n [6.5        3.75       2.83333333 2.375     ] /n
4. Hasil Pembagian dari vektor VD dan vektor VC adalah =/n [[0.9        0.35       0.16666667]
 [1.90909091 1.40909091 1.24242424]] /n
PERKALIAN DOT VEKTOR
1. Hasil Perkalian dot vektor dari vektor VB dan vektor VA adalah =/n 340 /n
2. Hasil Perkalian dari vektor VC dan vektor VD adalah